### ISSUE TITLE
Add exception

### ISSUE THREAD

**Issue by enjoijkee** [kentor/react-click-outside#15]
Hi! Can I define some element as exception of handleClickOutside? 
I need to prevent this function when I click on specific element.

Thanks!

**Comment by kentor** [comment]
`handleClickOutside` takes the event as the first argument:

```js
handleClickOutside(e) {
  if (e.target...) { // test something with e.target (the element clicked)
  }
}
```

**Comment by enjoijkee** [comment]
Nice, thanks!
