### ISSUE TITLE
How to test components with react-click-outside

### ISSUE THREAD

**Issue by nerdymax** [kentor/react-click-outside#19]
When a component is exported with `enhanceWithClickOutside`, enzyme can't find the component in it.

For example, the following fails:
```javascript
test('Renders the root div', () => {
  const component = shallow(<MyComponent />);
  expect(component).toContain('div#root-div');
});
```

`MyComponent.js`
```javascript
function MyComponent() {
  // ...
  return (
    <div id="root-div">
      {/* ... */}
    </div>
  );
}
export default enhanceWithClickOutside(MyComponent)
```

What is the workaround?

**Comment by kentor** [comment]
This is a general issue with higher order components. Better to ask at the enzyme project.

Resources:
https://github.com/airbnb/enzyme/issues/539
https://github.com/airbnb/enzyme/blob/e7226255bded93e285e36b50e16b59c8dc2458f9/docs/api/ShallowWrapper/dive.md

**Comment by hatched** [comment]
@nerdymax We don't use enzyme but you may find PR #25 and Issue #20 helpful for the approach we've taken.
