### ISSUE TITLE
Does position of component affect handleClickOutsided handler?

### ISSUE THREAD

**Issue by Tamba32** [kentor/react-click-outside#23]
I am running into a problem where handleClickOutside is called every time I click anywhere on screen, even when I am not clicking outside the component. 

Could this be due to the fact that my component is positioned absolutely and not statically or relatively?

**Comment by kentor** [comment]
The code uses `Node.contains()`

see:
https://github.com/kentor/react-click-outside/blob/master/index.js#L25
https://developer.mozilla.org/en-US/docs/Web/API/Node/contains


If it is triggering even when you are clicking "inside", you might not be really clicking inside if there is another layer that is actually "outside" that is rendered over it.
