### ISSUE TITLE
Unable to find node on an unmounted component in React 16.0.0

### ISSUE THREAD

**Issue by jagi** [kentor/react-click-outside#27]
I was trying to implement such a feature by myself but nothing worked as described on several websites. So I've encountered this package and it also does not work with React 16.0.0. I get the "Unable to find node on an unmounted component" error. Did anyone experience this problem?

It comes from usage of the `ReactDOM.findDOMNode` method. It's really strange because the component is mounted (I've checked that). Maybe it's a bug in React 16.0.0?

**Comment by kentor** [comment]
I upgraded the tests to use React 16. There is a test case called `does not call handleClickOutside when unmounted` that should end up calling `ReactDOM.findDOMNode(null)`, and there does not appear to be any problems with that.

**Comment by jagi** [comment]
Sorry, I forgot to close this issue. I found a source of the problem. It was because the project was using React 15 and components package that I'm writing was using React 16 and this error is thrown when React can't make a decision what React version to use.
