### ISSUE TITLE
This wrapper broke the prototype chain in inheritance

### ISSUE THREAD

**Issue by mytharcher** [kentor/react-click-outside#28]
Once a component is wrapped, it can't be inherited to access the parent prototype method. Here is the example code:

~~~javascript
@ClickOutside
class Parent extends React.Component {
  someMethod() {
    console.log('call parent');
  }
}

class Child extends Parent {}

console.log(Child.prototype.someMethod); // undefined
~~~

I think make one more layer inheritance for wrapping would be better.

**Comment by kentor** [comment]
Inheritance will not be supported. It's not a technique that is used at all in the React community.  https://reactjs.org/docs/composition-vs-inheritance.html

**Comment by mytharcher** [comment]
I do prefer composition than inheritance in most cases. But In some cases when you use a 3rd-party component, and want to extend it in some way (something like another way of rendering but keep 90% its behaviors), composition can't do that. And if it uses any HoC wrapper, you can only rewrite another with 90% same code without any reuse.

This article ([React Higher Order Components in depth](https://medium.com/@franleplant/react-higher-order-components-in-depth-cf9032ee6c3e)) also introduced extending components in 2 ways. I think as an HoC developer, should not break the possibility of deep component extending in any way. So I suggest to develop any HoC in inheritance way.

**Comment by kentor** [comment]
Is there an example of HoCs that don't break inheritance?

**Comment by mytharcher** [comment]
This gist could be an example:

https://gist.github.com/albertkawmi/fb50a922061eae2965004dfdc64dc506

I don't mean it is a must to change. Just provide some suggestion and edge usage. Whether change it or not, it is up to your consideration. No any offense.
