### ISSUE TITLE
ES6 classes do not have displayName (also a note about a newer ES7 feature)

### ISSUE THREAD

**Issue by sebinsua** [kentor/react-click-outside#3]
1. ES6 classes do not have `displayName` but they do have `name`. Maybe consider making `Wrapped${WrappedComponent.displayName}` be `ClickOutside(${WrappedComponent.displayName || WrappedComponent.name})`.

2. Also, [this might not be true](https://github.com/kentor/react-click-outside/blob/master/index.js#L5) if you like me [made `handleClickOutside` a class instance field](https://github.com/jeffmo/es-class-fields-and-static-properties#instance-field-declaration-process).

Not super important, but if you get time to fix please do. :)

**Comment by kentor** [comment]
Thanks. I admit I don't use ES6 classes for React, but I will look into this when I have some time.

**Comment by kentor** [comment]
Can you tell me why you're making `handleClickOutside` a class instance field rather than a prototype method on the class?

**Comment by sebinsua** [comment]
@kentor ES6+ broke autobinding and [class instance fields are probably the way that Facebook will be implementing this in future](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding).

**Comment by kentor** [comment]
Thanks for the insights! Both issues should be resolved in version 2.1.0.
