### ISSUE TITLE
How to wrap stateless component with react-click-outside?

### ISSUE THREAD

**Issue by gitowiec** [kentor/react-click-outside#33]
As said in topic, could You please provide example?
I use recompose and withHandlers.
All I got is error `Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.`

**Comment by kentor** [comment]
You can't as it stands. Why do you need it to be a stateless component?

**Comment by ADagen** [comment]
Sorry guys for interrupting you, but you can.

@gitowiec as you already use `recompose`, just unleash the power of <del>Pandora's box</del> [lifecycle](https://github.com/acdlite/recompose/blob/master/docs/API.md#lifecycle):

```javascript
const yourEnhancer = compose(
    withHandlers({
        someHandler: () => () => console.log('Hurray, it works!'),
    }),
    ...

    withClickOutside,
    lifecycle({
        handleClickOutside() {
            this.props.someHandler();
        },
    }),

    ...
),

```

@kentor how do you feel about add this to the README.md? Sure this trick is't limited to `recompose`,  one can use any suitable HOCs.
