### ISSUE TITLE
Make react-click-outside event listener configurable so that it can be attached to event bubbling phase rather than capturing phase.

### ISSUE THREAD

**Issue by prashantagarwal** [kentor/react-click-outside#36]
In most of the scenarios listening to event capturing does make sense. But in certain complex components, it would be cool if it could rely on event bubbling phase rather than capturing phase.
Let me know if you need specific use case. I will send a PR if this is sounds reasonable.

**Comment by kentor** [comment]
Use cases would be nice...

**Comment by syropian** [comment]
For me, I have a dropdown rendered in an iframe. Clicking outside the iframe triggers the `handleClickOutside` method, but clicking anywhere in the iframe does not. I don't suppose there's currently a way around this?

**Comment by gggritso** [comment]
I have an interesting one where a `Popover` is wrapped in `withClickOutside` to close it, but there are some components that, when clicked, should _not_ close `Popover`. I’d like to do that by stopping propagation on those components, but it’s tough if the click outside event handler is using capturing.

**Comment by kentor** [comment]
@gggritso I would suggest not using `stopPropagation` to stop, since the effect is _very_ implicit, and very far from where click outside is called. Maybe something like an explicit exclusion would work better, see: https://github.com/kentor/react-click-outside/issues/15
