### ISSUE TITLE
TypeError: hoistNonReactStatic is not a function

### ISSUE THREAD

**Issue by annmirosh** [kentor/react-click-outside#39]
Thanks for awesome hoc. I get this error when I try to use it: "TypeError: hoistNonReactStatic is not a function".

I'd be really thankfull if you could take a look at this issue.

This is repo with code for reproducing : https://github.com/annmirosh/react-click-outside-bug

Thanks

**Comment by kentor** [comment]
ugh, related to this package https://github.com/mridgway/hoist-non-react-statics/issues/52

**Comment by kentor** [comment]
I think it works now, but you might need to remove your node_modules directory and reinstall packages to get a working version of the `hoist-non-react-statics` package
