### ISSUE TITLE
Support for react 15?

### ISSUE THREAD

**Issue by DanielSundberg** [kentor/react-click-outside#7]
When building with react 15 I get the following error:

````html
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'react/lib/Object.assign' in C:\Code\......\my_proj\node_modules\react-onclickoutside
````

Changing __line 2__ in _decorator.js_ to:

    var objectAssign = require('object.assign');

solves the problem.

**Comment by kentor** [comment]
wrong repository. you're looking for react-onclickoutside

**Comment by DanielSundberg** [comment]
So sorry, I clicked the wrong google link
