### ISSUE TITLE
stopPropagation

### ISSUE THREAD

**Issue by bryanph** [kentor/react-click-outside#8]
In the docs the following caught my eye:

> Using the event capturing phase prevents elements with a click handler that calls stopPropagation from cancelling the click event that would eventually trigger the component's handleClickOutside function.

Isn't the described situation not what you would want? When I call stopPropagation in some click handler I expect handleClickOutside not to be called?

**Comment by kentor** [comment]
Having click outside cancelled due to stop propagation is usually a bug. See: https://css-tricks.com/dangers-stopping-event-propagation/

If you want handleClickOutside not to do anything then have a conditional inside that makes it a no-op.
